
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 953915
  host: localhost

development:
  <<: *default
  database: ComicsLibrary_development

test:
  <<: *default
  database: ComicsLibrary_test

production:
  <<: *default
  database: ComicsLibrary_production
  username: ComicsLibrary
  password: <%= ENV["COMICSLIBRARY_DATABASE_PASSWORD"] %>
